# Generated by Django 2.1.4 on 2018-12-29 08:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2018, 12, 29, 8, 4, 24, 481121, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_passed',
            field=models.DateField(default=datetime.datetime(2018, 12, 29, 8, 4, 24, 481121, tzinfo=utc)),
        ),
    ]
