# Generated by Django 2.0.9 on 2019-01-20 08:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='count',
            field=models.PositiveSmallIntegerField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
