# Generated by Django 2.0.9 on 2019-01-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_participant_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
