# Generated by Django 2.0.9 on 2019-01-20 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0003_auto_20190120_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='count',
        ),
    ]
