# Generated by Django 2.2.4 on 2019-08-22 13:54

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cover', models.ImageField(blank=True, upload_to='projects/%Y/%m/%d/')),
                ('img1', models.ImageField(blank=True, null=True, upload_to='projects/%Y/%m/%d/')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='projects/%Y/%m/%d/')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='projects/%Y/%m/%d/')),
                ('img4', models.ImageField(blank=True, null=True, upload_to='projects/%Y/%m/%d/')),
                ('img5', models.ImageField(blank=True, null=True, upload_to='projects/%Y/%m/%d/')),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True)),
                ('technologies', multiselectfield.db.fields.MultiSelectField(choices=[('web', 'Web Development'), ('app', 'App Development')], max_length=7)),
                ('stack', models.CharField(max_length=255)),
                ('year', models.DateField()),
                ('repo_link', models.CharField(max_length=255)),
                ('team', models.ManyToManyField(to='profiles.UserProfile')),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
    ]
