# Generated by Django 2.1.4 on 2018-12-29 08:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='year',
            field=models.DateField(default=datetime.datetime(2018, 12, 29, 8, 5, 41, 326963, tzinfo=utc)),
        ),
    ]
