# Generated by Django 2.0.9 on 2018-12-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('photograph', models.ImageField(blank=True, upload_to='review/%Y/%m/%d/')),
                ('designation', models.CharField(max_length=128)),
                ('company', models.CharField(max_length=128)),
                ('department', models.CharField(max_length=120)),
                ('comments', models.CharField(max_length=255)),
            ],
        ),
    ]
