# Generated by Django 2.0.13 on 2019-03-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postreview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='photograph',
            field=models.ImageField(blank=True, upload_to='templates/postreview/%Y/%m/%d/'),
        ),
    ]
